// This file is automatically generated. Do not modify.
// This file is used to store the Firebase configuration object.
// It is used by the Firebase initialization file.
export const firebaseConfig = {"projectId":"stat-responder","appId":"1:894047572469:web:a1cb9c90f744ab9d9fd0bc","apiKey":"AIzaSyBwRa0EFHRqr7051VeEykf96mJ5Rlm1YIA","authDomain":"stat-responder.firebaseapp.com","measurementId":"","messagingSenderId":"894047572469","storageBucket":"stat-responder.appspot.com"};
